### ISSUE TITLE
[Support] Industrial Foregoing

### ISSUE THREAD

**Issue by EvanHsieh0415** [Mango-Minecraft-Project/MoreCreateRecipes-Datapack#12]
## TODO
- [ ] Industrial Foregoing (`industrialforegoing`)
  - [ ] redyed
    - index: range 0 - 15
    - [ ] `laser_len{index}`
  - [ ] alloy
    - [ ] `pink_slime_ingot`

## Notes
...
