### ISSUE TITLE
[Support] Immersive Engineering

### ISSUE THREAD

**Issue by EvanHsieh0415** [Mango-Minecraft-Project/MoreCreateRecipes-Datapack#13]
## TODO
- [ ] Immersive Engineering (`immersiveengineering`)
  - [ ] craft
    - [ ] `treated_wood_horizontal`
  - [ ] alloy
    - material: `electrum` / `constantan` / `steel`
    - [ ] `ingot_{material}`
  - [ ] redyed
    - [ ] `sheetmetal_colored_{color}`

## Notes
...
