### ISSUE TITLE
[Feature] Farmer's Delight

### ISSUE THREAD

**Issue by EvanHsieh0415** [Mango-Minecraft-Project/MoreCreateRecipes-Datapack#7]
## TODO
- [ ] Farmer's Delight (`farmersdelight`)
  - [ ] redyed
    - [ ] `{color}_canvas_sign`
  - [ ] undyed
    - [ ] `canvas_sign`
  - [ ] cutting board
    - [ ] wild vegetable
      - vegetable: `cabbages` / `onions` / `tomatoes` / `carrots` / `potatoes` / `beetroots` / `rice`
      - [ ] `wild_{vegetable}`
    - [ ] slice
      - food: `pumpkin` / `cod` / `cooked_cog` / `salmon` / r`cooked_salmon` / `cake` / `apple_pie` / `sweet_berry_cheesecake` / `chocolate`
      - [ ] `{food}_slice`
    - [ ] flower
    - [ ] leather armor
      - item: `helmet` / `chest` / `leggings` / `boots` / `horse_armor`
      - [ ] `leather_{item}`
      - [ ] `saddle`
    - [ ] tree bark
      - log: `oak` / `spruce` / `birch` / `jungle` / `acacia` / `dark_oak`
      - [ ] `#minecraft:{log}_logs`
      - nether_log: `crimson` / `warped`
      - [ ] `#minecraft:{nether_log}_stem`
  - [ ] drink
    - [ ] `hot_cocoa`
    - [ ] `melon_juice`

## Notes
...
